3 задача
Alexander-Ploskin/MathMechReposSemester2 pull request #3
Opened 2020-02-18 10:14 UTC by Alexander-Ploskin

2020-02-23 09:36 UTC, yurii-litvinov requested changes
Надо ещё .csproj, по имеющимся файлам проект не собрать

2020-02-23 09:36 UTC, yurii-litvinov commented on HW1/1.3/Program.cs
> +        }
Надо пустую строчку после метода

2020-02-23 09:36 UTC, yurii-litvinov commented on HW1/1.3/Program.cs
> +            }
Это лучше foreach

2020-02-23 09:36 UTC, yurii-litvinov commented on HW1/1.3/Program.cs
> +                array[i] = int.Parse(Console.ReadLine());
Бонусное задание --- почитать про string.Split и сделать, чтобы массив можно было вводить в одну строчку и вообще не вводить его длину

2020-02-23 11:02 UTC, Alexander-Ploskin commented
Почему-то foreach в PrintArray начинает итерироваться с 1 и пытается выйти за границы массива. Разумного объяснения этому я не нашел, поэтому вернул for.

2020-03-02 08:21 UTC, yurii-litvinov approved these changes
Ок, зачтена

2020-03-04 17:26 UTC, merged